### PR TITLE
Added some seriously code-golfed samples

### PR DESCRIPTION
**Pull request by alion02**

### CODE REVIEW

**Comment by alion02** [comment]
Feel free to reject this PR if you don't want to add more samples or for any other reason - I don't particularly care either way. I just felt like sharing some heavy language abuse ✔️

**Comment by ddorn** [comment]
Thank you for those beautiful codes golfed examples!

**Comment by aaronduino** [comment]
No way, these code samples are awesome! I'll merge as soon as possible

**Comment by alion02** [comment]
I'm also spreading the language a bit over on [code-golf](https://codegolf.stackexchange.com/):
- [Fibonacci](https://codegolf.stackexchange.com/a/169932/74965)
- [Factorial](https://codegolf.stackexchange.com/a/169952/74965)
- [Evilness](https://codegolf.stackexchange.com/a/170446/74965)

**Pull request merged**
